repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    args: ["--allow-multiple-documents"]
  - id: mixed-line-ending
  - id: sort-simple-yaml
  - id: file-contents-sorter
  - id: trailing-whitespace
    files: ^\.github/workflows/|.*\.py$

# Python formatting
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black

# Python linter (Flake8)
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    files: chromo/[^_].*\.py
    args: [--config, setup.cfg]