# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Test daemonflux

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'README.*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [native, arm64]
        py: [cp 37, cp38, cp39, cp310, cp311, cp312]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Install package and deps
      run: python -m pip install --prefer-binary -v .[test]
    - name: Run tests
      run: pytest -vv
    - name: Build package
      run: python -m build